### ISSUE TITLE
T-Deck build takes some resets to boot up.

### ISSUE THREAD

**Issue by mirkokral** [bwhitman/tulipcc#184]
Serial: https://pastebin.com/raw/ZUx2v116

**Comment by bwhitman** [comment]
Ah, seems to be #154 again

I can take a look. Just to confirm are you using the latest release ? ( tulip.upgrade() )

**Comment by mirkokral** [comment]
@bwhitman 
Hello there, even after flashing the newest release, connecting to wifi, upgrading and resetting i still get the resets.

**Comment by bwhitman** [comment]
@mirkokral thanks! I will investigate this some more later this week.

**Comment by bwhitman** [comment]
I did a quick look and got it to crash by doing a few resets. I found this thread https://github.com/espressif/esp-idf/issues/9411 which led me to think it's something with GPIO on display startup. So I just dumbly added some delays and also turned off a vestigial GPIO set. I haven't been able to get it to crash on boot since. If you're able to compile Tulip, give this a go -- otherwise you'll see this fix in the next big release (probably in a couple of weeks). 

```
diff --git a/tulip/esp32s3/tdeck_display.c b/tulip/esp32s3/tdeck_display.c
index 94cc115d..f1295ed6 100644
--- a/tulip/esp32s3/tdeck_display.c
+++ b/tulip/esp32s3/tdeck_display.c
@@ -85,8 +85,8 @@ void run_tdeck_display(void) {
         .pin_bit_mask = 1ULL << TDECK_LCD_BK_LIGHT_GPIO
     };
     gpio_config(&bk_gpio_config);
-    gpio_set_level(TDECK_LCD_BK_LIGHT_GPIO, 0);
-
+    //gpio_set_level(TDECK_LCD_BK_LIGHT_GPIO, 0);
+    delay_ms(50);
     // turn on TDeck peripheral 
     gpio_config_t peri_gpio_config = {
         .mode = GPIO_MODE_OUTPUT,
@@ -94,6 +94,7 @@ void run_tdeck_display(void) {
     };
     gpio_config(&peri_gpio_config);
     gpio_set_level(TDECK_PERI_GPIO, 1);
+    delay_ms(50);
 
     // set up SPI
     spi_bus_config_t buscfg = {
```

**Comment by bwhitman** [comment]
This fix is now committed to main
